### ISSUE TITLE
2/10 Status Update

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#11]

**Comment by Simulacrum0** [comment]
1.) Skip the Hertz/Speed for now if troubling.  Really not too significant as we continuously do timings and intstruction sets work differently so its just a rough estimate...not terribly important.

2.) Am seeing the problem...quite surprised w/ WinRT...( i think this must be your StackOverflow link: http://stackoverflow.com/questions/13881173/windows-store-app-system-information ).  Seems like their API model envisions much more plug'n'play hardware model w/ cores, speeds, memories, etc. changing rapidly ( & yet no event-based notifications, just polling afaik/afaics? ).  This seems to be the approach needed ( https://msdn.microsoft.com/en-us/library/windows/apps/jj553431.aspx ).  We *will* need it, but it is 'ok' to just return the minimal RAM allowed for now, which seems to be 1GB for now: 

*Processor: 1 gigahertz (GHz) or faster with support for PAE, NX, and SSE2 (more info)
RAM: 1 gigabyte (GB) (32-bit) or 2 GB (64-bit)
Hard disk space: 16 GB (32-bit) or 20 GB (64-bit)
Graphics card: Microsoft DirectX 9 graphics device with WDDM driver*

Keep this task open and return when time suggest or you are otherwise stuck.

Nice setup and ops w/ the Git Status btw.  Well done+

**Comment by Simulacrum0** [comment]
Btw, the code below is Posix code for Cpu Freq in Hz if helpful...again its fine to postpone that work as its not critical, but we'll need it eventually:

   size_t length;
   int mib[6];
   int result;

   mib[0] = CTL_HW;
   mib[1] = HW_CPU_FREQ;
   length = Tbytes_u( result );

   if( sysctl(mib, 2, &result, &length, NULL, 0 ) < 0 )
   {
     Log( "Err:getting cpu frequency\n" ); return;
   }
  Log( "CPU Frequency = %d hz\n", result );
