### ISSUE TITLE
Grab RAM specs

### ISSUE THREAD

**Issue by mindaptiv** [mindaptiv/Foster#4]
CURRENT REQUIREMENTS:
-return minimum supported RAM size for WinRT

OLD REQUIREMENTS:
-make
-model
-size in bytes as unsigned 64 bit int
-speed 32 bit float in hz
-additional L1/L3 cache information

**Comment by Scrubsauce** [comment]
WinRT-Win32 compatibility references:
https://msdn.microsoft.com/en-us/library/windows/apps/br205757.aspx
https://msdn.microsoft.com/en-us/library/windows/apps/dn424765.aspx

**Comment by Scrubsauce** [comment]
No apparent soln. as of January 2015:
http://stackoverflow.com/questions/28230710/how-to-get-ram-size-in-windows-metro

**Comment by Scrubsauce** [comment]
Possible alternatives:

ASHWID:
https://msdn.microsoft.com/en-us/library/windows/apps/jj553431.aspx 

ASHWID uses bytes:
https://code.msdn.microsoft.com/windowsapps/How-to-use-ASHWID-to-3742c83e

Pinvoke:
http://stackoverflow.com/questions/13881173/windows-store-app-system-information

**Comment by Scrubsauce** [comment]
@Simulacrum0 
Component: Memory
Byte-Stream representation (four bytes): 02-00-XX-XX

02-00 in byte-stream denotes the following values are for memory.

"The byte stream consists of multiple groups of four bytes. The first two bytes contain the type of the component and the next two bytes contain the value. Use the table below to identify the type of each component:"

Example from MSDN ASHWID sample (given in hex by MS):
02-00-D8-78

Examples from ASHWID documentation (given in decimal by MS, translated to hex via wolfram alpha):
2,0,162,217  ==(hex)==> 02-00-A2-D9

2,0,162,217  ==(hex)==> 02-00-A2-D9

2,0,226,37    ==(hex)==> 02-00-E2-25

2,0,162,255  ==(hex)==> 02-00-A2-FF

Converting each byte into binary:
A2 ==(binary)==> 1010 0010
D9 ==(binary)==> 1101 1001
E2 ==(binary)==> 1110 0010
25 ==(binary)==> 0010 0101
FF ==(binary)==> 1111 1111
D8 ==(binary)==> 1101 1000
78 ==(binary)==> 0111 1000

Adding the two bytes together in either decimal or hex form yields unhelpful numbers (not significant in terms of usual storage sizes, etc.), nor would I expect MS to have you add two bytes together to get total memory, but then again, MS.  If they were meant to be summed, you'd assume that the first byte would be maxed out at FF, and the second byte would be whatever was leftover, however, only one example has FF as its last byte.

Instead, try concatenating the bytes together to form a new binary/decimal number:
A2D9 =(decimal)=> 41,689
E225 =(decimal)=> 57,893
A2FF =(decimal)=> 41,727 
D878 =(decimal)=> 55,416

None of which immediately stand out to me as appropriate numbers for memory or fractional system memory:
41,000 kilobytes would only be .041gigabytes, which is really low by today's standards
41,000 bits would only be about 5 kilobytes
41,000 gigabytes is just ridiculous
I feel like I'm missing something really obvious...its not a case of big-endian/little-endian drama is it?  Been a long time since I've encountered that.

The 02-00 are identifiers and should not contribute to the value according to the documentation.

If I include 02-00 as part of the value:
0200A2D9 = 33,596,159

If that's bits, that still only comes out to about 4.2 MB, still feels really small.

Conversion isn't the problem, its making sense of the values so I can provide a proper measurement that's causing confusion.

**Comment by Simulacrum0** [comment]
Just finished our Biz call, so before i resumed code i figured i'd reply-

Perhaps reorder the bytes as suggested in the Bu4_u() code from this morning...so instead of A2FF its FFA2 ( each pair of Hexvalues can be swapped )...FFA2 is close to 64K, which might be 64MiB?  That might give you nothing though...given the minimum RAM on WinRT is 1GiB ~= 1<<30 i don't see that value coming through in any of those numbers... Might the interpretation be in different chunks? Like memory page sizes ( 4K ) or something else.  Any sample code on MSDN?

**Comment by Simulacrum0** [comment]
Ok, on your first ASHWID link above, they indicate the second two byte value following the first is merely an id. Nothing to get from it other than 'unique ID' for that device.  We'll have to find a way to convert that ID into some further query or other means to get data.  _Or_ just return the WinRT minimum for now and move on.  That would be fine.

 it is a fail if i'm researching this instead of doing code, so i gotta bail, but good luck-

**Comment by Simulacrum0** [comment]
Ugly: looks like we aren't able to get Harddrives, Sizes, or much of any info in WinRT:

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/ced6ed38-2037-4052-92ee-1ec0d15efba8/systemunauthorizedaccesexception-while-using-getfolderfrompathasync?forum=winappswithcsharp

So pls just return the minimum specs for now and Essence will handle fails when sizes are exceeded...Strange design.

**Comment by Scrubsauce** [comment]
Currently returning the Win8.1 OS minimum sys req of 1GB = 1 billion bytes as a uint64

**Comment by Scrubsauce** [comment]
Win 8.1 Specs:
http://windows.microsoft.com/en-US/windows-8/system-requirements
