### ISSUE TITLE
Determine any Additional Conversions Necessary

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#55]
Please see Cylon.h for variable definitions:

https://github.com/mindaptiv/Foster/wiki/Structures#cylonh  
https://github.com/mindaptiv/Foster/blob/master/Cylon.h

Remaining variable types that I have not converted to fit a requirement handed down by @Simulacrum0:
- unsigned int
- bool
- float32
- DWORD
- WORD
- BYTE
- SHORT
- long
- void*
- std::list

If any of these are not preferred or if any specific ones should be changed (i.e. "please make this int a float instead") please let me know and I'll proceed with #1. -Thanks

**Comment by Simulacrum0** [comment]
1) the Cylon.h Structs look good...aside from the std:: string/list folks...but we can fix that later. So pls keep them for now and we'll address down the road.

2) As for mappings, its probably useful to understand what we're mapping to.

Basically we have signed ints, unsigned ints, floats, bit masks ( still unsigned ints, but treated differently ), and addresses.  That's all the ways to use 'byte storage' on a computer imho...everything else is an aggregate ( strings, structs, fancy-data-structures list std:list, etc. ).

In Essence, its i, u, f, q, & a for i=int (signed), u=unsigned(int), f=float, q=quality (bitmask), and p=address(pointer).  There are currently 6 sizes 1byte =b, 2byte = s (short), 4byte = (no prefix, 32bit word size), 8byte = d (double word, 64bits), 16byte = x ( Xtra large ), 

You may also see a 'v' for vector/array/constant pointer to a fixed size instead of 'p' as well as 'k' for 'constant' mean read-only.

Putting them together gets us

bu, su, u, du, xu
bi, si, i, di, xi
bf, sf, f, df, xf ( note bf & sf & xf require special handling )
bq, sq, q, dq, xq

You do NOT need to use the Essence naming convention.  
Seriously.
But you do need to be know the size/format that you use ( thats the only requirement )
i recommend using <stdint.h> to enable known sizes for each compiler platform and to have a consistent standard.

Here's a possible mapping

bool        -> uint32 -> Yes_t  ( can be stored as byte, short, int, long long pending function need or storage need)

float32 -> F32 -> F_t
double -> F64 -> Df_t
(Note: you should not need byte-float, short float in your work)

UBYTE -> unsigned byte -> uint8 -> Bu_t
WORD -> unsigned short -> uint16 - > Su_t
DWORD-> unsigned int -> uint32 -> U_t
unsigned int  -> uint32 -> U_t
long unsigned int  -> uint64 -> Du_t

BYTE -> signed byte -> int8 -> Bi_t
SHORT -> short integer -> int16 -> Si_t
long -> signed integer -> int32 -> I_t
long long -> signed long long -> int64 -> Di_t

void\* -> generally a 64bit pointer for all platforms ( 32 on earlier Android/iOS ).  Void_tp

std::list will have to be done manually later

**Comment by Simulacrum0** [comment]
Here's the actual mapping we use, which maps either <stdint.h> or makes C compiler assumptions to get fixed sizes & formats to use in structs:

//=====================================
// NATIVE NUMBERS
//=====================================
#ifdef _STDINT_H_

//%%%
//8
typedef uint8_t Bu_t;
typedef int8_t Bi_t;

//%%%
//16
typedef uint16_t  Su_t;
typedef int16_t Si_t;
typedef float16_t Sf_t;

//%%%
//32
typedef uint32_t U_t;
typedef int32_t I_t;
typedef float F_t;

//%%%
//64
typedef uint64_t Du_t;
typedef int64_t Di_t;
typedef double Df_t;

//%%%
//128
typedef uint128_t Xu_t;
typedef int128_t Xi_t;
typedef long double Xf_t;

#else

//%%%
//8
typedef unsigned char Bu_t;
typedef signed char Bi_t;

//%%%
//16
typedef unsigned short  Su_t;
typedef signed short Si_t;
typedef float16_t Sf_t;

//%%%
//32
typedef unsigned int U_t;
typedef signed int I_t;
typedef float F_t;

//%%%
//64
typedef uint64_t Du_t;
typedef int64_t Di_t;
typedef double Df_t;

//%%%
//128
typedef uint128_t Xu_t;
typedef int128_t Xi_t;
typedef long double Xf_t;

#endif

**Comment by Scrubsauce** [comment]
Call at 9 to make sure I understand correctly, sounds good.

I got as far as Su in the list at first and now I just imagine you're coding with a bunch of Krana
![krana](https://cloud.githubusercontent.com/assets/2531841/6598523/e82f3d92-c7c9-11e4-8bc4-de270f0c0793.jpeg)
![krana2](https://cloud.githubusercontent.com/assets/2531841/6598561/1f08b668-c7ca-11e4-85f7-442348b5a6a8.jpg)
![krana-possessed](https://cloud.githubusercontent.com/assets/2531841/6598579/3dd7dc68-c7ca-11e4-9bdd-043d9a7cb3c9.png)

**Comment by Simulacrum0** [comment]
Ah how times have changed...
![jpeg-3](https://cloud.githubusercontent.com/assets/8696781/6600011/503af9bc-c7e3-11e4-9029-1b739c10cf23.jpeg)
